name: Deploy Worker

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-worker.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # deploy-worker.yml
      - name: Deploy
        run: cd api && flyctl deploy --remote-only -a suaagenda-worker --dockerfile Dockerfile.worker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}